include: package:very_good_analysis/analysis_options.5.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    # avoid_dynamic_calls: false
analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
  errors:
    invalid_annotation_target: ignore