// Autogenerated from Pigeon (v10.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "pigeon.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface MyMessage ()
+ (MyMessage *)fromList:(NSArray *)list;
+ (nullable MyMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation MyMessage
+ (instancetype)makeWithTitle:(NSString *)title
    body:(NSString *)body
    email:(NSString *)email
    test:(NSNumber *)test {
  MyMessage* pigeonResult = [[MyMessage alloc] init];
  pigeonResult.title = title;
  pigeonResult.body = body;
  pigeonResult.email = email;
  pigeonResult.test = test;
  return pigeonResult;
}
+ (MyMessage *)fromList:(NSArray *)list {
  MyMessage *pigeonResult = [[MyMessage alloc] init];
  pigeonResult.title = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.title != nil, @"");
  pigeonResult.body = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.body != nil, @"");
  pigeonResult.email = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.email != nil, @"");
  pigeonResult.test = GetNullableObjectAtIndex(list, 3);
  NSAssert(pigeonResult.test != nil, @"");
  return pigeonResult;
}
+ (nullable MyMessage *)nullableFromList:(NSArray *)list {
  return (list) ? [MyMessage fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.title ?: [NSNull null]),
    (self.body ?: [NSNull null]),
    (self.email ?: [NSNull null]),
    (self.test ?: [NSNull null]),
  ];
}
@end

@interface MessageApiCodecReader : FlutterStandardReader
@end
@implementation MessageApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [MyMessage fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface MessageApiCodecWriter : FlutterStandardWriter
@end
@implementation MessageApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[MyMessage class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface MessageApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation MessageApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[MessageApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[MessageApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *MessageApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    MessageApiCodecReaderWriter *readerWriter = [[MessageApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void MessageApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<MessageApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.khaltitask.MessageApi.getMessages"
        binaryMessenger:binaryMessenger
        codec:MessageApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getMessagesFromEmail:error:)], @"MessageApi api (%@) doesn't respond to @selector(getMessagesFromEmail:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_fromEmail = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSArray<MyMessage *> *output = [api getMessagesFromEmail:arg_fromEmail error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
